### PR TITLE
Bug: Fixed blink of unauthed content

### LINKED ISSUE #18: [BUG] Blink of unauthed content when logged in
**Observed behavior**
When the logged-in user hit the `/signin` page he sees a flash of page content and then he is redirected to the `/notes` page.

**Expected behavior**
When the logged-in user hit the `/signin` he sees the loading state and then he is redirected to the `/notes` page. Or more ideal case is to redirect him on the server side.

### PR DESCRIPTION
**Pull request by rollakal**

### CODE REVIEW

**Review by MatejVykoukal — CHANGES_REQUESTED** [review]
The logic seems good, but please abstract it to a new component(`PublicRoute`) similar to `ProtectedRoute`, since it will be user multiple times in future

File: src/Components/PublicRoute.tsx [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+  const { status } = useSession();
+
+  useEffect(() => {
+    if (status == "authenticated") {
+      void router.push("/notes");
+    }
+  }, [status]);
+  
+  const renderPublicRoute = () => {
+    if (status === "authenticated") {
```
Comment (MatejVykoukal) [inline src/Components/PublicRoute.tsx]: Here should probably be status loading, right? :)

**Review by MatejVykoukal — CHANGES_REQUESTED** [review]

File: src/Components/PublicRoute.tsx (hunk 1 above)
Comment (rollakal) [reply src/Components/PublicRoute.tsx]: Yes this works aswell. Gonna change it.

**Review by MatejVykoukal — APPROVED** [review]
